name: Nix check

on:
  pull_request:
  push:
    branches: [master]

jobs:
  home-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix build .#homeConfigurations.kirill.activationPackage --no-link
